name: Setup repository for CI tests
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .tool-versions

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
